import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#f7f8fa",
        surface: "#ffffff",
        "surface-dim": "#d9dee7",
        "surface-bright": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f1f4f2",
        "surface-container": "#e8ece9",
        "surface-container-high": "#e1e6e2",
        "surface-container-highest": "#d9dfda",
        "surface-variant": "#e5e9e6",
        "on-surface": "#171c1a",
        "on-surface-variant": "#4c5751",
        "on-background": "#171c1a",
        "inverse-surface": "#2b312e",
        "inverse-on-surface": "#edf2ef",
        outline: "#748079",
        "outline-variant": "#c8d0cb",
        "surface-tint": "#006d44",
        primary: "#1d4ed8",
        "on-primary": "#ffffff",
        "primary-container": "#dbeafe",
        "on-primary-container": "#1e3a8a",
        "inverse-primary": "#60a5fa",
        brand: "#006d44",
        "brand-container": "#d9f7e8",
        "on-brand-container": "#005232",
        secondary: "#6b38d4",
        "on-secondary": "#ffffff",
        "secondary-container": "#eee7ff",
        "on-secondary-container": "#5516be",
        tertiary: "#0d9488",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#ccfbf1",
        "on-tertiary-container": "#115e59",
        error: "#dc2626",
        "on-error": "#ffffff",
        "error-container": "#fee2e2",
        "on-error-container": "#991b1b",
        won: "#059669",
        "won-container": "#d1fae5",
        activated: "#7c3aed",
        "activated-container": "#ede9fe",
        complex: "#3b82f6",
        "complex-container": "#eff6ff",
        density: "#14b8a6",
        "density-container": "#f0fdfa",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.875rem",
        "2xl": "1.25rem",
        full: "9999px",
      },
      spacing: {
        base: "4px",
        xs: "8px",
        sm: "16px",
        md: "24px",
        lg: "32px",
        xl: "48px",
        gutter: "24px",
        "container-max": "1440px",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "display-lg": [
          "48px",
          { lineHeight: "60px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" },
        ],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "data-mono": ["14px", { lineHeight: "20px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
