import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#f4f6fb",
        surface: "#ffffff",
        "surface-dim": "#d8e0f0",
        "surface-bright": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eef2fa",
        "surface-container": "#e4eaf6",
        "surface-container-high": "#d9e2f2",
        "surface-container-highest": "#ced9ee",
        "surface-variant": "#dce4f4",
        "on-surface": "#0f172a",
        "on-surface-variant": "#475569",
        "on-background": "#0f172a",
        "inverse-surface": "#1e293b",
        "inverse-on-surface": "#f1f5f9",
        outline: "#64748b",
        "outline-variant": "#cbd5e1",
        "surface-tint": "#1d4ed8",
        primary: "#1d4ed8",
        "on-primary": "#ffffff",
        "primary-container": "#93c5fd",
        "on-primary-container": "#1e3a8a",
        "inverse-primary": "#60a5fa",
        secondary: "#475569",
        "on-secondary": "#ffffff",
        "secondary-container": "#e2e8f0",
        "on-secondary-container": "#334155",
        tertiary: "#7c3aed",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#ddd6fe",
        "on-tertiary-container": "#5b21b6",
        error: "#dc2626",
        "on-error": "#ffffff",
        "error-container": "#fee2e2",
        "on-error-container": "#991b1b",
        won: "#059669",
        "won-container": "#d1fae5",
        activated: "#7c3aed",
        "activated-container": "#ede9fe",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "4px",
        xs: "8px",
        sm: "16px",
        md: "24px",
        lg: "32px",
        xl: "48px",
        gutter: "24px",
        "container-max": "1440px",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "display-lg": [
          "48px",
          { lineHeight: "60px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" },
        ],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "data-mono": ["14px", { lineHeight: "20px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
